<?php 
//error_reporting(0);
	//accessing session applied
	session_start();
    
	//Database connection
	include '../database/config.php';
	
	//Redirecting user back to login if not logged in
	$email = $_SESSION['email'];

    if(!isset($email)){
        header('location:../login.php');
    }

    if(isset($_POST['submit'])){

        $names = mysqli_real_escape_string($conn, $_POST['names']);
        $type = mysqli_real_escape_string($conn, $_POST['type']);
        $email = mysqli_real_escape_string($conn, $_POST['email']);
        $title = mysqli_real_escape_string($conn, $_POST['title']);
        $message = mysqli_real_escape_string($conn, $_POST['message']);
        
        // We need to check if the account with that email name exists.
        $select_students = mysqli_query($conn, "SELECT * FROM `message` WHERE title = '$title'") or die('query failed');
 
        if(mysqli_num_rows($select_students) > 0){
            $fail[] = 'Sorry, the same title or questions already exist!';
        }else{
            //Student id is auto generated by system
            mysqli_query($conn, "INSERT INTO `message`(title, names, type, email, message) VALUES('$title', '$names', '$type', '$email', '$message')") or die('Query failed');
            $success[] = 'Your post was sent successful!';
    }
        
    }
     
//Code for deleting post
if(isset($_GET['delete'])){
    $id = $_GET['delete'];
    mysqli_query($conn, "DELETE FROM `message` WHERE id = '$id'") or die('query failed');
    header('location: discussions.php');
 }

?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Student Portal | Dashboard</title>
        <link rel="shortcut icon" href="icons/icons8-windows-xp-30.png">
        <link rel="stylesheet" href="../css/bootstrap.min.css" media="screen" ><!--FRAMEWORK-->
        
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"><!--ICONS-->
       
        <link rel="stylesheet" href="../css/dash1.css"><!--Dashboard design-->
        <link rel="stylesheet" href="../css/topnavbar.css"><!--nav design-->

        <!-- Custom styles for this template -->
        <link href="../css-forums/dashboard-main.css" rel="stylesheet">
        <link href="../css-forums/messages.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="../css-forums/popup_form.css"/>

       
    <style>
 .message{
   
   max-width: 1200px;
   background-color: blue;
   padding:1rem;
   display: flex;
   align-items: center;
   justify-content: space-between;
   border-radius: 3px;
   margin-top: 5px;
}


.message span{
   font-size: 1.5rem;
   color: white;
}

.message i{
   cursor: pointer;
   color: white;
   font-size: 1.5rem;
}

.message i:hover{
   transform: rotate(90deg);
}

/**FOR STYLING THE CONTENTS OF THE BODY**/
.dashboard .box-container{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(19rem, 1fr));
  gap:0.8rem;
  max-width: 1200px;
  margin:15px auto;
  align-items: flex-start;
  items-align:left;
}

.dashboard .box-container .box{
  border-radius: .5rem;
  background-color: var(--white);
  box-shadow: var(--box-shadow);
  border: 1px solid powderblue;
  text-align: center;
}

.dashboard .box-container .box h3{
  font-size: 2.0rem;
  color:var(--black); 
}

.dashboard .box-container .box p{
  margin-top: 2.0rem;
  padding:1rem;
  color:var(--white);
  font-size: 1.5rem;
  border-radius: .0rem;
  
}

    </style>
<body>
    <!--Start of navbar -->
    <div class="nav">
        <input type="checkbox" id="nav-check">
        <div class="nav-header">
            <div class="nav-title">
                ORACLE GATES
            </div>
        </div>
        <div class="nav-btn">
            <label for="nav-check">
                <span></span>
                <span></span>
                <span></span>
            </label>
        </div>
  
        <div class="nav-links">
            <a href="../resources/chapter1-oci-introduction.php">Learning Resources</a>
            <a href="../logout.php"><i class="fa fa-sign-out"></i> Logout</a>
           
            
        </div>
    </div>
    

        <section class="dashboard" >
            <div style="padding: 10px; background: powderblue;">
                <p><h3>Discussion Forums || <a href="#create-thread.php" class="btn btn-default" style="float:right;" data-toggle="modal" data-target="#form_modal"><i class="fa fa-plus"></i> Create Thread</a> </h3></p>
            </div>
            <!--Success messages--->
            <?php
                                    if(isset($success)){
                                        foreach($success as $success){
                                        echo '
                                            <div class="message">
                                                <span>
                                                    <strong>
                                                        <i class="fa fa-check" style=""></i> 
                                                    </strong>
                                                    '.$success.'
                                                </span>
                                                <i class="fa fa-times" onclick="this.parentElement.remove();"></i>
                                            </div>
                                        ';
                                        }
                                    }
                                ?>

                                <!--Fail messages--->
                                <?php
                                    if(isset($fail)){
                                        foreach($fail as $fail){
                                        echo '
                                            <div class="message" style="background-color: red;">
                                                <span>
                                                    <strong>
                                                        <i class="fa fa-warning" style=""></i> 
                                                    </strong>
                                                    '.$fail.'
                                                </span>
                                                <i class="fa fa-times" onclick="this.parentElement.remove();"></i>
                                            </div>
                                        ';
                                        }
                                    }
                                ?>

            <div class="box-container">

                <?php
                    $order_query = mysqli_query($conn, "SELECT * FROM `message` WHERE email='$email'") or die('query failed');
                    if(mysqli_num_rows($order_query) > 0){
                        while($fetch_message = mysqli_fetch_assoc($order_query)){
                ?>
                <div class="box"  style="border-radius: 2px;">
                    <button class="collapsible"><i class="fa fa-user"></i> 
                        <span style=""> : <?php echo $fetch_message['title']; ?></span>    
                    </button>
         
                    <div class="content">
                      <div style="margin-left: 20px; margin-right: 10px; float:left; text-align:left; font-size: 14px;">
                        <font>From : <span><?php echo $fetch_message['names']; ?></span> </font><br>
                        <font>Date : <span><?php echo $fetch_message['date']; ?></span> </font><br>
                        <font>Email : <span><?php echo $fetch_message['email']; ?></span> </font><br>
                        <font><b style="float:left;">Message </b>:
                            <br><br>
                            <span><?php echo $fetch_message['message']; ?></span> <br><br>
                        </font>
                        
                        <div style="word-spacing: 0px; font-size: 18px;">
                            <br>
                            <a href="discussions.php?delete=<?php echo $fetch_message['id']; ?>" title="Delete Post" class="btn btn-warning" style="margin-left: 10px; " onclick="return confirm('Are you sure to DELETE this Thread ?');" >
                               <i class="fa fa-trash"></i> Delete Post</a>
                            </a>
                            <br>
                            <hr>
                            <p style="font-size: 16px;">
                                <div style="background: powderblue;padding: 10px;">
                                    <i class="fa fa-comment-o"> Respnses</i>
                                </div>

                                <i class="fa fa-user" style="font-size: 16px;"> Kefuoe Sole || Admin </i> 
                                
                                <?php
                                $select_messages = mysqli_query($conn, "SELECT * FROM `respond_message` WHERE email='$email' ") or die('query failed');
                                    if(mysqli_num_rows($select_messages) > 0){
                                        while($fetch = mysqli_fetch_assoc($select_messages)){
                            ?>
                            <br><br>
                            <div  style="border-radius: 2px;">
                                <div style="float:left; text-align:left; font-size: 14px;">
                                    <span> <?php echo $fetch['message']; ?></span> <br><br>
                                </div>
                            </div>
                                <?php
                                    }
                                    }else{
                                        echo '<p class="empty">Currently there are replies yet</p>';
                                    }
                                ?>
                            </p>
                            
                            <br>
                            
                        </div>
                      </div>
                      
                    </div>
                     
                </div>
                
                <?php
                        }
                    }else{
                        echo '<p class="empty">Currently there are no messages yet</p>';
                    }
                ?>
            </div>
            <br><br>
        </section>

<!--MESSAGE RESPONSE FORM -->
<div class="modal fade" id="form_modal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<form method="POST" action="">
				<div class="modal-header" style="background-color: powderblue;">
					<h3 class="modal-title">RESPONSE MESSAGE</h3>
				</div>
				<div class="modal-body">
					<div class="col-md-2"></div>
					<div class="col-md-8">
						<div class="form-group">
							<label>Title / Question /Suggest</label>
							<textarea  type="textarea" type="text" class="form-control" name="title" required="required"/>
                            
                            </textarea>
                        </div>
                        
                        <div class="form-group">
                            <select type="text" name="type" class="form-control" required>
                                <option value="student">Student</option>
                            </select>
                        </div>

                        <div class="form-group">
							<label>Full Names</label>
							<input type="text" class="form-control" name="names" required="required"/>
						</div>
                        
                        <div class="form-group">
							<label>Your Email</label>
							<input type="email" class="form-control" name="email" required="required"/>
						</div>
						
                        <div class="form-group">
							<label>Message</label>
							<textarea  type="textarea" class="form-control" name="message"  required="required"/>
              
                            </textarea>
						</div>
            
					</div>
				</div>
				<br style="clear:both;"/>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-danger"><span class="fa fa-remove"></span> Cancel</button>
					<button class="btn btn-primary" name="submit"><span class="fa fa-send-o"></span> Forward</button>
				</div>
			</form>
		</div>
	</div>
</div>	
<!--END OF MESSAGE RESPONSE-->



<script src="../js/bootstrap.bundle.min.js"></script>
<script src="../js/jquery-3.2.1.min.js"></script>	
<script src="../js/jquery/jquery-2.2.4.min.js"></script>
<script src="../js/bootstrap/bootstrap.min.js"></script><!--Pop up form-->


<!--Collapse div content-->
<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    } 
  });
}
</script>	
</body>
</html>